<?php

/**
 * BaseNews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property clob $description
 * @property clob $text
 * @property text $meta_title
 * @property text $meta_keywords
 * @property text $meta_description
 * 
 * @method string getTitle()            Returns the current record's "title" value
 * @method clob   getDescription()      Returns the current record's "description" value
 * @method clob   getText()             Returns the current record's "text" value
 * @method text   getMetaTitle()        Returns the current record's "meta_title" value
 * @method text   getMetaKeywords()     Returns the current record's "meta_keywords" value
 * @method text   getMetaDescription()  Returns the current record's "meta_description" value
 * @method News   setTitle()            Sets the current record's "title" value
 * @method News   setDescription()      Sets the current record's "description" value
 * @method News   setText()             Sets the current record's "text" value
 * @method News   setMetaTitle()        Sets the current record's "meta_title" value
 * @method News   setMetaKeywords()     Sets the current record's "meta_keywords" value
 * @method News   setMetaDescription()  Sets the current record's "meta_description" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNews extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('news');
        $this->hasColumn('title', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('text', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('meta_title', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('meta_keywords', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('meta_description', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'description',
              2 => 'text',
              3 => 'meta_title',
              4 => 'meta_keywords',
              5 => 'meta_description',
             ),
             ));
        $sluggable1 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             'unique' => true,
             'type' => 'string',
             'builder' => 
             array(
              0 => 'Slug',
              1 => 'slugify',
             ),
             'indexName' => 'slugNews',
             'uniqueBy' => 
             array(
              0 => 'title',
             ),
             ));
        $i18n0->addChild($sluggable1);
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}