<?php

/**
 * BaseTeam
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $surname
 * @property text $description
 * @property string $photo
 * @property text $biography
 * @property text $post
 * @property text $meta_title
 * @property text $meta_keywords
 * @property text $meta_description
 * @property Doctrine_Collection $CategorysPhoto
 * 
 * @method string              getName()             Returns the current record's "name" value
 * @method string              getSurname()          Returns the current record's "surname" value
 * @method text                getDescription()      Returns the current record's "description" value
 * @method string              getPhoto()            Returns the current record's "photo" value
 * @method text                getBiography()        Returns the current record's "biography" value
 * @method text                getPost()             Returns the current record's "post" value
 * @method text                getMetaTitle()        Returns the current record's "meta_title" value
 * @method text                getMetaKeywords()     Returns the current record's "meta_keywords" value
 * @method text                getMetaDescription()  Returns the current record's "meta_description" value
 * @method Doctrine_Collection getCategorysPhoto()   Returns the current record's "CategorysPhoto" collection
 * @method Team                setName()             Sets the current record's "name" value
 * @method Team                setSurname()          Sets the current record's "surname" value
 * @method Team                setDescription()      Sets the current record's "description" value
 * @method Team                setPhoto()            Sets the current record's "photo" value
 * @method Team                setBiography()        Sets the current record's "biography" value
 * @method Team                setPost()             Sets the current record's "post" value
 * @method Team                setMetaTitle()        Sets the current record's "meta_title" value
 * @method Team                setMetaKeywords()     Sets the current record's "meta_keywords" value
 * @method Team                setMetaDescription()  Sets the current record's "meta_description" value
 * @method Team                setCategorysPhoto()   Sets the current record's "CategorysPhoto" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTeam extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('team');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('surname', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('photo', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('biography', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('post', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('meta_title', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('meta_keywords', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('meta_description', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CategoryPhoto as CategorysPhoto', array(
             'local' => 'id',
             'foreign' => 'team_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'surname',
              2 => 'biography',
              3 => 'post',
              4 => 'description',
              5 => 'meta_title',
              6 => 'meta_keywords',
              7 => 'meta_description',
             ),
             ));
        $sluggable1 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'surname',
             ),
             'unique' => true,
             'type' => 'string',
             'builder' => 
             array(
              0 => 'Slug',
              1 => 'slugify',
             ),
             'indexName' => 'slugTeam',
             'uniqueBy' => 
             array(
              0 => 'lang',
             ),
             ));
        $i18n0->addChild($sluggable1);
        $this->actAs($i18n0);
    }
}