<?php

/**
 * BasePractice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property text $text
 * @property text $meta_title
 * @property text $meta_keywords
 * @property text $meta_description
 * 
 * @method string   getName()             Returns the current record's "name" value
 * @method text     getText()             Returns the current record's "text" value
 * @method text     getMetaTitle()        Returns the current record's "meta_title" value
 * @method text     getMetaKeywords()     Returns the current record's "meta_keywords" value
 * @method text     getMetaDescription()  Returns the current record's "meta_description" value
 * @method Practice setName()             Sets the current record's "name" value
 * @method Practice setText()             Sets the current record's "text" value
 * @method Practice setMetaTitle()        Sets the current record's "meta_title" value
 * @method Practice setMetaKeywords()     Sets the current record's "meta_keywords" value
 * @method Practice setMetaDescription()  Sets the current record's "meta_description" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePractice extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('practice');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('text', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('meta_title', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('meta_keywords', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('meta_description', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'text',
              2 => 'meta_title',
              3 => 'meta_keywords',
              4 => 'meta_description',
             ),
             ));
        $sluggable1 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'unique' => true,
             'type' => 'string',
             'builder' => 
             array(
              0 => 'Slug',
              1 => 'slugify',
             ),
             'indexName' => 'slugPractice',
             'uniqueBy' => 
             array(
              0 => 'lang',
             ),
             ));
        $i18n0->addChild($sluggable1);
        $this->actAs($i18n0);
    }
}