<?php

/**
 * ArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Article');
    }

    public function getLastArticle($count = 1){

        $query = Doctrine_Query::create()
            ->from('Article a')
            ->limit($count)
            ->orderBy('a.created_at DESC');
        if ($count > 1) {
            
            return $query->execute();
        } else {

            return $query->fetchOne();
        }
    }

    public function findBySlug($slug)
    {
        $q = Doctrine_Query::create()
        ->from('Article a')
        ->leftJoin('a.Translation t')
        ->where('t.slug = ?',$slug);
     return $q->fetchOne();
    }

    public static function getArticleDesc()
    {
       $query = Doctrine_Query::create()
        ->from('Article a')
        ->orderBy('a.updated_at DESC');
        return $query;
    }
}
