<?php

/**
 * CategoryPhotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryPhotoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryPhotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoryPhoto');
    }

    public function findBySlug($slug)
    {
        $q = Doctrine_Query::create()
        ->from('CategoryPhoto c')
        ->leftJoin('c.Translation t')
        ->where('t.slug = ?',$slug);
     return $q->fetchOne();
    }
}