<?php

/**
 * CategoryShowcaseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryShowcaseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryShowcaseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoryShowcase');
    }

    public function findBySlug($slug)
    {
        $q = Doctrine_Query::create()
        ->from('CategoryShowcase c')
        ->leftJoin('c.Translation t')
        ->where('t.slug = ?',$slug);
     return $q->fetchOne();
    }
}