<?php

/**
 * MassageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MassageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MassageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Massage');
    }

     public function findBySlug($slug)
    {
        $q = Doctrine_Query::create()
        ->from('Massage m')
        ->leftJoin('m.Translation t')
        ->where('t.slug = ?',$slug);
     return $q->fetchOne();
    }
}