<?php

/**
 * PracticeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PracticeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PracticeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Practice');
    }

     public function findBySlug($slug)
    {
        $q = Doctrine_Query::create()
        ->from('Practice p')
        ->leftJoin('p.Translation t')
        ->where('t.slug = ?',$slug);
     return $q->fetchOne();
    }
}