<?php

/**
 * ShowcaseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShowcaseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShowcaseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Showcase');
    }

    public function findBySlug($slug)
    {
        $q = Doctrine_Query::create()
        ->from('Showcase s')
        ->leftJoin('s.Translation t')
        ->where('t.slug = ?',$slug);
     return $q->fetchOne();
    }
}
