<?php

/**
 * TeamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TeamTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TeamTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Team');
    }

    public function findBySlug($slug)
    {
        $q = Doctrine_Query::create()
        ->from('Team t')
        ->leftJoin('t.Translation tt')
        ->where('tt.slug = ?',$slug);
     return $q->fetchOne();
    }
}