# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

homepage_localized:
  url:   /:sf_culture/
  param: { module: default, action: index }
  requirements:
    sf_culture: (?:ru|uk)

# generic rules
# please, remove them by adding more specific rules
practices:
  url:   /:sf_culture/practice.html
  param: { module: practice, action: index }
practice:
  url:   /:sf_culture/practice/:slug.html
  param: { module: practice, action: show }
massages:
  url:   /:sf_culture/massage.html
  param: { module: massage, action: index }
massage:
  url:   /:sf_culture/massage/:slug.html
  param: { module: massage, action: show }
price:
  url:   /:sf_culture/price.html
  param: { module: page, action: spages }
timetable:
  url:   /:sf_culture/timetable.html
  param: { module: page, action: spages }
contacts:
  url:   /:sf_culture/contacts.html
  param: { module: default, action: sendmess }
photogalery:
  url:   /:sf_culture/photogalery.html
  param: { module: photogalery, action: index}
photos:
  url:   /:sf_culture/photogalery/:slug.html
  param: { module: photogalery, action: show}
team:
  url:   /:sf_culture/team.html
  param: { module: team, action: index}
member:
  url:   /:sf_culture/team/:slug.html
  param: { module: team, action: show}
showcase:
  url:   /:sf_culture/showcase/:parent_slug/:slug.html
  param: { module: showcase, action: showShowcase}
category_showcases:
  url:   /:sf_culture/showcase.html
  param: { module: showcase, action: index}
category_showcase:
  url:   /:sf_culture/showcase/:slug.html
  param: { module: showcase, action: show}
news_show:
  url:   /:sf_culture/news/:slug.html
  param: { module: news, action: show}
news:
  url:   /:sf_culture/news.html
  param: { module: news, action: index}
article:
  url:   /:sf_culture/article/:slug.html
  param: { module: article, action: show}
articles:
  url:   /:sf_culture/article.html
  param: { module: article, action: index}
default_index:
  url:   /:sf_culture/:module
  param: { action: index }

default:
  url:   /:sf_culture/:module/:action/*
