all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=magic161_namaste'
      username: magic161
      password: '7mTYDFN'
      attributes:
        default_table_collate: utf8_general_ci
        default_table_charset: utf8