generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Practice
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          practice
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display:  [name, slug]
      filter:  ~
      form:    ~
      edit:
        title: Edit "%%name%%"
      new:     ~
